language: java
jdk: oraclejdk8

#https://dzone.com/articles/travis-ci-tutorial-java-projects
cache:
  directories:
  - $HOME/.m2

install:
- mvn -N io.takari:maven:wrapper

before_script:
  - psql -c "CREATE DATABASE test;" -U postgres

branches:
  only:
  - master

notifications:
  email: false